"""Exact target-only CHECK recovery admission; no live DB/container access."""
import copy
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import Mock

import private_restore_honcho_checks as subject


class ChecksTests(unittest.TestCase):
    def test_known_roundtrip_changes_are_two_exact_parse_trees(self):
        source=subject.expected(); target=subject.expected(restored=True)
        self.assertNotEqual(source,target)
        self.assertEqual(subject.admitted_target(source,target),[0,1])
        self.assertEqual(subject.admitted_target(source,source),[])
        target['checks'][0]=copy.deepcopy(source['checks'][0])
        self.assertEqual(subject.admitted_target(source,target),[1])

    def test_employee_third_family_uses_observed_catalog_and_target_only_repair(self):
        # Literal source/pg_restore deparse and production model's String(16):
        # the new family's test input is not generated by expected().
        table={'schema':'public','name':'ortak_employee_reviewed_operations','owner':'ortak_honcho',
            'kind':'r','column':'action','type':'character varying(16)','not_null':True,'identity':'','generated':''}
        check={'table':table['name'],'name':'ck_ortak_employee_reviewed_operations_action_kind',
            'definition':"CHECK (action::text = ANY (ARRAY['publish'::character varying, 'withdraw'::character varying]::text[]))",
            'validated':True,'local':True,'inheritance_count':0,'no_inherit':False,
            'deferrable':False,'deferred':False,'columns':['action']}
        source=subject.expected()
        source['tables'].insert(0,table);source['checks'].insert(0,check)
        target=copy.deepcopy(source)
        target['checks'][0]['definition']="CHECK (action::text = ANY (ARRAY['publish'::character varying::text, 'withdraw'::character varying::text]))"
        command=Mock();command.psql=lambda database:['psql',database]
        command.run.return_value=json.dumps(source).encode()
        self.assertEqual(subject.source_checks(command,'selected','00000001-00000002-3'),source)
        sql=command.run.call_args.kwargs['sql']
        self.assertIn("('ortak_employee_reviewed_operations','action')",sql)
        self.assertIn("SET TRANSACTION SNAPSHOT '00000001-00000002-3'",sql)
        self.assertEqual(source,subject.expected(employee=True))
        self.assertEqual(subject.admitted_target(source,target),[2])
        self.assertEqual(subject.admitted_target(source,subject.expected(restored=True,employee=True)),[2,0,1])
        for group,key,changed in [('tables','type','character varying(17)'),('tables','owner','other'),
            ('checks','name','renamed'),('checks','validated',False),
            ('checks','definition',target['checks'][0]['definition'].replace("'withdraw'","'expire'"))]:
            invalid=copy.deepcopy(target);invalid[group][0][key]=changed
            with self.subTest(key=key),self.assertRaises(subject.Refused): subject.admitted_target(source,invalid)
        for partial in ({'tables':[table],'checks':[check]},subject.expected()):
            with self.assertRaises(subject.Refused): subject.admitted_target(source,partial)
        with self.assertRaises(subject.Refused): subject.admitted_target(subject.expected(),target)
        command.run.return_value=json.dumps({'tables':[table],'checks':[check]}).encode()
        with self.assertRaises(subject.Refused): subject.source_checks(command,'selected')
        with tempfile.TemporaryDirectory() as directory:
            root=Path(directory);root.chmod(0o700)
            command=self.command(root,target=target,after=source)
            result=subject.repair_checks(command,command.honcho_check_restore_authority,source)
            self.assertEqual(result['changed_checks'],[check['name']])
            self.assertFalse(result['source_mutations']);self.assertFalse(result['schema_comparison_normalized'])
            repair=command.run.call_args_list[1].kwargs['sql']
            self.assertEqual(repair.count('DROP CONSTRAINT'),1)
            self.assertIn('ALTER TABLE public.'+table['name']+' ADD CONSTRAINT '+check['name']+
                " CHECK (action IN ('publish', 'withdraw'));",repair)
            self.assertIn(subject.guard_sql(target),repair);self.assertIn(subject.guard_sql(source),repair)

    def test_any_unknown_owner_schema_column_type_or_constraint_semantics_refuse(self):
        baseline=subject.expected(restored=True)
        edits=[('tables',0,'owner','other'),('tables',0,'schema','other'),
            ('tables',0,'name','other'),('tables',0,'type','text'),('tables',0,'not_null',False),
            ('checks',0,'name','renamed'),('checks',0,'validated',False),
            ('checks',0,'no_inherit',True),('checks',0,'inheritance_count',1),
            ('checks',0,'columns',['action','request_hash']),('checks',0,'definition','CHECK (true)'),
            ('checks',0,'definition',baseline['checks'][0]['definition'].replace("'expire'","'unknown'"))]
        for group,index,key,value in edits:
            row=copy.deepcopy(baseline);row[group][index][key]=value
            with self.subTest(key=key,value=value),self.assertRaises(subject.Refused):
                subject.admitted_target(subject.expected(),row)
        for target in [dict(baseline,unknown=True),dict(baseline,checks=[]),
                       dict(baseline,checks=baseline['checks']*2),dict(baseline,tables=[])]:
            with self.assertRaises(subject.Refused): subject.admitted_target(subject.expected(),target)

    def test_source_is_original_or_complete_legacy_absence_only(self):
        empty={'tables':[],'checks':[]}
        self.assertEqual(subject.admitted_target(empty,empty),[])
        with self.assertRaises(subject.Refused): subject.admitted_target(empty,subject.expected())
        with self.assertRaises(subject.Refused): subject.admitted_target(subject.expected(restored=True),subject.expected())

    def command(self, root, target=None, after=None):
        command=Mock()
        command.root=root
        command.honcho_check_restore_authority='ortak_honcho_verify_'+'a'*32
        command.psql=lambda database: ['psql',database]
        command.run=Mock(side_effect=[json.dumps(target or subject.expected(restored=True)).encode(),b'',
            json.dumps(after or subject.expected()).encode()])
        return command

    def test_fresh_capability_consumed_before_repair_and_sql_guard_spans_transaction(self):
        with tempfile.TemporaryDirectory() as directory:
            root=Path(directory);root.chmod(0o700)
            command=self.command(root);database=command.honcho_check_restore_authority
            result=subject.repair_checks(command,database,subject.expected())
            self.assertIsNone(command.honcho_check_restore_authority)
            self.assertFalse(result['schema_comparison_normalized'])
            sql=command.run.call_args_list[1].kwargs['sql']
            self.assertTrue(sql.startswith('BEGIN;'))
            self.assertTrue(sql.endswith('COMMIT;\n'))
            self.assertEqual(sql.count('DROP CONSTRAINT'),2)
            self.assertIn("CHECK (action IN ('publish', 'withdraw', 'expire'))",sql)
            self.assertIn(subject.guard_sql(subject.expected(restored=True)),sql)
            self.assertIn(subject.guard_sql(subject.expected()),sql)
            with self.assertRaises(subject.Refused): subject.repair_checks(command,database,subject.expected())
            self.assertEqual(command.run.call_count,3)

    def test_no_source_or_occupied_target_capability_and_no_blind_replay(self):
        for database,authority in [('ortak_honcho_adapter_test',None),('ortak_honcho_verify_'+'a'*32,None),
                                   ('unrelated','unrelated')]:
            command=Mock(spec=['honcho_check_restore_authority','run'])
            command.honcho_check_restore_authority=authority
            with self.subTest(database=database),self.assertRaises(subject.Refused):
                subject.repair_checks(command,database,subject.expected())
            command.run.assert_not_called()

    def test_changed_target_refuses_before_any_ddl_and_failed_final_shape_is_retained(self):
        with tempfile.TemporaryDirectory() as directory:
            root=Path(directory);root.chmod(0o700)
            target=subject.expected(restored=True);target['checks'][0]['validated']=False
            command=self.command(root,target=target)
            with self.assertRaises(subject.Refused):
                subject.repair_checks(command,command.honcho_check_restore_authority,subject.expected())
            self.assertEqual(command.run.call_count,1)
            command=self.command(root,after=subject.expected(restored=True))
            with self.assertRaises(subject.Refused):
                subject.repair_checks(command,command.honcho_check_restore_authority,subject.expected())
            self.assertTrue((root/'honcho-check-repair-intent.json').is_file())
            self.assertFalse((root/'honcho-check-repair-complete.json').exists())


if __name__=='__main__': unittest.main()
